### ISSUE TITLE
Why is Hikari set to `isAutoCommit = false`

### ISSUE THREAD

**Issue by nhalase** [raharrison/kotlin-ktor-exposed-starter#106]
Also, shouldn't the `newSuspendedTransaction {}` block in `DatabaseFactory` be using `Dispatchers.IO`? That's how JetBrains does it in the [Ktor docs](https://ktor.io/docs/interactive-website-add-persistence.html#queries).

Mostly, I'm just wondering why you would want Hikari set to `isAutoCommit = false`.

Thanks!

**Comment by raharrison** [comment]
Yep thanks, should be using `Dispatchers.IO` will update that.

As for the `autoCommit` it was/is due to the fact that Exposed requires all queries to be run within a transaction anyway, so it will always manage the commit itself. Ref below issue which also discusses it more. Having auto-commit set to true by default on the connections Hikari creates and then Exposed setting it to false every time isn't great performance wise so I set it straight on the pool config.

The situation might be different now but I can still see the same code segments in place. Really is just an Exposed thing as opposed to anything else with Ktor/Hikari etc.

https://github.com/JetBrains/Exposed/issues/306

Which references https://github.com/JetBrains/Exposed/blob/master/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt

**Comment by nhalase** [comment]
Thanks for the insight! I feel like Exposed should provide a bit more FAQ on their wiki about that potentiality. Really helpful, though!
